### PR TITLE
mrc-665: add a proxy to the constellation

### PR DESCRIPTION
**Pull request by richfitz**
This PR will add a basic nginx proxy to the constellation. Currently this uses only a self-signed certificate, hopefully @weshinsley can organise us a real cert and later we can update it with the proper hostname (mrc-666).

(We need a real cert up so that we can get ICT to open ports, etc).

### CODE REVIEW

**Comment by richfitz** [comment]
I was thinking it's November and we were previously asked to get something up ASAP so we could just move forward on this and then change things over - I'm not sure what the timeline is on getting things set up at the UNAIDS end, but it presumably could grind on a bit. It'll take a while for ICT to open the ports in the firewall too, and for that we need the service up running so they can test it.

**Comment by richfitz** [comment]
(we'll also want a staging server I'm presuming, and the domain name matters less there)

**Comment by hillalex** [comment]
Ok, sure. I think it'll be very quick at the UNAIDS side - they just have to buy an SSL cert and create a DNS record. But if we want SSL for a staging server then makes sense. Do we not have a wildcard certificate for *.imperial.dide.ic.ac.uk?

**Comment by richfitz** [comment]
Unfortunately not - each subdomain is individually done

**Comment by richfitz** [comment]
Wes is investigating the situation here - it's possible that ICT can do all the https stuff for us

**Pull request merged**
